language: java
jdk:
- openjdk11
branches:
  only:
  - master
install:
# groff has a lot of recommended dependencies that are not needed for html
- sudo apt-get install -y --no-install-recommends groff
script:
- make check
- make dist
before_deploy:
- mkdir pages
- cp javae.html pages/index.html
deploy:
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: pages
  on:
    jdk: openjdk11
